"use strict";
exports.__esModule = true;
var index_1 = require("../index");
index_1["default"].note("test start");
index_1["default"].line();
index_1["default"].split();
index_1["default"].line(2);
index_1["default"].info("this is info");
index_1["default"].success("this is success");
index_1["default"].warning("this is warning");
index_1["default"].error("this is error");
index_1["default"].plain("this is plain");
